name: psp2_fn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_naver_map: ^1.4.1+1
  kakao_flutter_sdk_user: ^1.9.7+3
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  video_player: ^2.10.1
  shared_preferences: ^2.2.3
  geolocator: ^13.0.1
  uni_links: ^0.5.1
  supercluster: ^3.2.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  uni_links:
    path: packages/uni_links

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/welcome_sc/
    - lib/assets/icons/mascot_character/
    - lib/assets/icons/app_icon/
    - lib/assets/icons/markers/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/app_icon/app_icon.jpeg"
